set(0,'DefaultTextFontName','Times',...
'DefaultTextFontSize',10,...
'DefaultAxesFontName','Times',...
'DefaultAxesFontSize',8,...
'DefaultLineLineWidth',1,...
'DefaultLineMarkerSize',7.75);
%%
load('tsp_Pd_vs_radar_SNR_v3.mat')
for ii = 2
    figure()
    linestyle = ["-","--","-.",":","--","-."];
    linecolor = 'bkrgcm';
    edgecolor = 'rmybkc';
    linemarker = ["+",".","*","x","s","o"];
    %plot(vu,PD_co(ii,:),'Color',linecolor(1),'Marker',char(linemarker(1)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(1),'LineStyle',char(linestyle(1)),...
    plot(vu,PD_co(ii,:),'Color',linecolor(1),'LineStyle',char(linestyle(1)),...
        'LineWidth',1.3,'DisplayName','Proposed with cooperation');
    hold on
%     plot(vu,PD_co_wc(ii,:),'Color',linecolor(2),'Marker',char(linemarker(2)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(2),'LineStyle',char(linestyle(2)),...
    plot(vu,PD_co_wc(ii,:),'Color',linecolor(2),'LineStyle',char(linestyle(2)),...
        'LineWidth',1.3,'DisplayName','Proposed without cooperation');
    hold on
%     plot(vu,PD_uc(ii,:),'Color',linecolor(3),'Marker',char(linemarker(3)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(3),'LineStyle',char(linestyle(3)),...
    plot(vu,PD_uc(ii,:),'Color',linecolor(3),'LineStyle',char(linestyle(3)),...
        'LineWidth',1,'DisplayName','Uncoded with coop');
    hold on
%     plot(vu,PD_uc_wc(ii,:),'Color',linecolor(4),'Marker',char(linemarker(4)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(4),'LineStyle',char(linestyle(4)),...
    plot(vu,PD_uc_wc(ii,:),'Color',linecolor(4),'LineStyle',char(linestyle(4)),...
        'LineWidth',1.3,'DisplayName','Uncoded without cooperation');
    hold on
%     plot(vu,PD_rc(ii,:),'Color',linecolor(5),'Marker',char(linemarker(5)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(5),'LineStyle',char(linestyle(5)),...
    plot(vu,PD_rc(ii,:),'Color',linecolor(5),'LineStyle',char(linestyle(5)),...
        'LineWidth',1.3,'DisplayName','Randomly coded with cooperation');
    hold on
%     plot(vu,PD_rc_wc(ii,:),'Color',linecolor(6),'Marker',char(linemarker(6)),'MarkerSize',5,'MarkerEdgeColor',edgecolor(6),'LineStyle',char(linestyle(6)),...
    plot(vu,PD_rc_wc(ii,:),'Color',linecolor(6),'LineStyle',char(linestyle(6)),...
        'LineWidth',1.3,'DisplayName','Randomly coded without cooperation');
    hold off
    grid on
    axis square
    xlabel('$\nu$','Interpreter','latex','FontSize',14)
    ylabel('$\mathrm{P}_\mathrm{d}$','Interpreter','latex','FontSize',14);
    a = get(gca,'XTickLabel');
    set(gca,'XTickLabel',a,'FontName','Times','fontsize',14)
    legend('FontSize',8,'Location','northeast');
    legend('boxoff');
end
% LegendCell = cell(length(SNR_Btr),1);
%legend(['\omega = [',num2str(omega_1),']';'\omega = [',num2str(omega_2),']'])
%legend({strcat('\omega = [',num2str(omega_1'),']'),strcat('\omega = [',num2str(omega_2'),']')});
%legend(LegendCell,'Interpreter','latex');
%legend('Interpreter','latex');
print('-depsc2','-r150','tsp_pd_vs_vu.eps')